# Site settings
title: Eduard's Blog
email: eduardvdbent@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  evanderbent


# Build settings
markdown: kramdown
comments: true